### ISSUE TITLE
fatal error: Adafruit_I2CDevice.h: No such file or directory

### ISSUE THREAD

**Issue by duojianghuji** [3gyptian/esphome-mlx90614-i2c_IR_temp_sensor#3]
Hi,
I tried to follow your instructions, but something wrong happened. it shows "Adafruit_I2CDevice.h: No such file or directory" It has been a long since I have been stuck in. Can you help to tackle it? I'm running the ESPHome version(2021.12.4)
![image](https://user-images.githubusercontent.com/66355796/145512823-60a2ef66-3fdd-4809-b27c-94b34bdc67e4.png)

**Comment by DerEmder** [comment]
Same here. It's now one year and still no answer?

**Comment by 3gyptian** [comment]
Sorry on the lag getting back folks. I never had this issue until I recently updated ESPHome and it seems to require additional libraries defined and in a different way.   I've updated the library references in mlx90614_example.yaml that will hopefully fix this for you as well.  Let me know if any problems as it's fresh on my mind and perhaps I can assist!  Cheers
