### ISSUE TITLE
I am getting the following error when trying to compile your example. And clues? :-)

### ISSUE THREAD

**Issue by srynearson** [3gyptian/esphome-mlx90614-i2c_IR_temp_sensor#4]
`/config/esphome/tssensor-new.yaml: In lambda function:
/config/esphome/tssensor-new.yaml:39:22: error: expected type-specifier before 'MLX90614'
       auto mlx = new MLX90614(5000);   
                      ^
/config/esphome/tssensor-new.yaml:41:78: error: could not convert '{<expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
       return {mlx->ambient_temperature_sensor, mlx->object_temperature_sensor};
                                                                              ^
Compiling /data/tssensor-new/.pioenvs/tssensor-new/lib64d/WiFi/WiFiSTA.cpp.o
Compiling /data/tssensor-new/.pioenvs/tssensor-new/lib64d/WiFi/WiFiScan.cpp.o
Compiling /data/tssensor-new/.pioenvs/tssensor-new/lib64d/WiFi/WiFiServer.cpp.o
*** [/data/tssensor-new/.pioenvs/tssensor-new/src/main.cpp.o] Error 1
========================= [FAILED] Took 35.34 seconds =========================`

**Comment by srynearson** [comment]
In file included from src/mlx90614.h:2:0,
                 from src/main.cpp:26:
/data/tssensor-new/.piolibdeps/tssensor-new/Adafruit MLX90614 Library/Adafruit_MLX90614.h:18:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

****************************************************************************
* Looking for Adafruit_I2CDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Adafruit_I2CDevice.h"
* Web  > https://registry.platformio.org/search?q=header:Adafruit_I2CDevice.h
*
****************************************************************************

compilation terminated.
In file included from /data/tssensor-new/.piolibdeps/tssensor-new/Adafruit MLX90614 Library/Adafruit_MLX90614.cpp:19:0:
/data/tssensor-new/.piolibdeps/tssensor-new/Adafruit MLX90614 Library/Adafruit_MLX90614.h:18:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

****************************************************************************
* Looking for Adafruit_I2CDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Adafruit_I2CDevice.h"
* Web  > https://registry.platformio.org/search?q=header:Adafruit_I2CDevice.h
*
****************************************************************************

compilation terminated.
*** [/data/tssensor-new/.pioenvs/tssensor-new/src/main.cpp.o] Error 1
*** [/data/tssensor-new/.pioenvs/tssensor-new/lib278/Adafruit MLX90614 Library/Adafruit_MLX90614.cpp.o] Error 1
========================= [FAILED] Took 34.34 seconds =========================

**Comment by 3gyptian** [comment]
Sorry on the lag getting back. I never had this issue until I recently updated ESPHome and it seems to require additional libraries defined and in a different way.   I've updated the library references in mlx90614_example.yaml that will hopefully fix this for you as well.  Let me know if any problems as it's fresh on my mind and perhaps I can assist!  Cheers
